version: "3.9"

services:
  server:
    build: .
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro

volumes:
  data:
