version: "3.9"

services: 

  server:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db  
    command: sh -c "sleep 10 && node server.js"
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '654321'
      POSTGRES_USER: 'teste'
    volumes:
      - data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql 
  
volumes:
  data: 




